### ISSUE TITLE
npm install doesn't work for @chrishenderson/mongodb-queue

### ISSUE THREAD

**Issue by marlonrosa** [cwhenderson20/aws-mocks#3]
Hey!! I'm trying to use that npm package on my project but when I do the `npm install -D aws-mocks` it doesn't work properly. I got that message from it: `no such package available : @chrishenderson/mongodb-queue`
I try to install it manually by `npm install @chrishenderson/mongodb-queue` and got the same error... but doing the `npm install mongodb-queue` It worked.
Any tips?

**Comment by cwhenderson20** [comment]
Hey @marlonrosa. Gee, that's odd. I'm not having the same issue. Could you potentially have a .npmrc file somewhere up the chain that's interfering with pulling from the public repository?

*Edit*: what version of npm are you running? (`npm -v`)

**Comment by marlonrosa** [comment]
Im using version 3.10.9

**Comment by cwhenderson20** [comment]
@marlonrosa, can you do me a favor and try to install @chrishenderson/mongodb-queue @ 2.0.4? I think it may have been an npm permissions issue.

**Comment by marlonrosa** [comment]
I keep getting the same error in old versions of node/npm to, the full error is: 
npm ERR! Linux 3.16.0-62-generic
npm ERR! argv "/home/marlon.rosa/.nvm/versions/node/v4.4.7/bin/node" "/home/marlon.rosa/.nvm/versions/node/v4.4.7/bin/npm" "install" "@chrishenderson/mongodb-queue@2.0.4"
npm ERR! node v4.4.7
npm ERR! npm  v2.15.8
npm ERR! code E404

npm ERR! 404 no such package available : @chrishenderson/mongodb-queue
npm ERR! 404 
npm ERR! 404 '@chrishenderson/mongodb-queue' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'bonuz-cnhub-notification-processor'
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! Please include the following file with any support request:

**Comment by cwhenderson20** [comment]
Two things:

1. Your error log shows that you're using npm version 2.15.8, not 3.10.9. Is this on a CI server? However, according to [this](https://docs.npmjs.com/getting-started/scoped-packages) article, 2.15.8 is a new enough version to work with scoped modules.
1. Maybe you're not logged in to the public registry? The article linked above mentions that you need to run `npm login` to use scoped packages.

I've had others try to install and they confirm that there are no issues. Can you try to find another scoped package (sorry, I don't have any off the top of my head) and see if the same issue occurs?

**Comment by marlonrosa** [comment]
Finally!! This tip about npm registry worked perfectly! I was using a private npm registry and now, without it, I could install that module. Thanks a lot!!

**Comment by cwhenderson20** [comment]
No problem! Glad you got it working.
